<a href="https://colab.research.google.com/github/porgill-prosper/airflow/blob/master/Tensors%20Crash%20Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>Tensors Crash Course</h1>

Tutorial 3.x

In [4]:
!pip3 install torch

In [0]:
import torch
import numpy as np

In [4]:
v = torch.tensor([1,2,3,4,5,6])
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [5]:
f = torch.FloatTensor([1,2,3,4,5,6])
print(f.size())

torch.Size([6])


In [6]:
v.view(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [10]:
a = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [0]:
numpy_cnv = tensor_cnv.numpy()


In [12]:
print(numpy_cnv)

[1 2 3 4 5]


In [19]:
t_one = torch.tensor([1,2,3])
t_two = torch.tensor([1, 2, 3])
dot_product = torch.dot(t_one, t_two)
print(dot_product)

tensor(14)


In [21]:
torch.linspace(0, 10, 5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])