<a href="https://colab.research.google.com/github/porgill-prosper/airflow/blob/master/Tensors%20Crash%20Course%20Tut3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>Tensors Crash Course</h1>

Tutorial 3.x

In [0]:
#!pip3 install torch

In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [9]:
one_d = torch.arange(0, 9)
one_d

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
two_d = one_d.view(3,3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [12]:
two_d.dim()

2

In [13]:
two_d[1,2]

tensor(5)

In [3]:
x = torch.arange(18).view(3,2,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [6]:
x[1, 0:2, 0:2]

tensor([[ 6,  7],
        [ 9, 10]])

In [13]:
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [17]:
mat_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3,2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [18]:
mat_a @ mat_b

tensor([[ 29, -16],
        [ 38,   6]])